/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout */

#ifndef _Included_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
#define _Included_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    shout_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_shout_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    shout_shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_shout_1shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    shout_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_shout_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    shout_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_shout_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    shout_get_error
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_shout_1get_1error
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    shout_get_errno
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_shout_1get_1errno
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    shout_get_connected
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_shout_1get_1connected
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    shout_set_host
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_shout_1set_1host
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    shout_set_port
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_shout_1set_1port
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    shout_set_agent
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_shout_1set_1agent
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    shout_set_user
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_shout_1set_1user
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    shout_set_password
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_shout_1set_1password
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    shout_set_mount
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_shout_1set_1mount
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    open
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_open
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout
 * Method:    shout_version
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_jpthiery_hermodr_broadcaster_infra_icecast_BindingLibShout_shout_1version
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
